### ISSUE TITLE
Cache created queries

### ISSUE THREAD

**Issue by Mateiadrielrafael** [EnderShadow8/wolf-ecs#11]
I sometimes want multiple systems to use the same query. Right now I just keep a record of queries around in my state, but this is pretty error prone. For example, I might realize system X needs access to component Y as well (which is not in the query system X uses), so now I need to check if anyone else is using the query system X uses, and if the answer is yes, create a different query which has all the components in the previous one + Y. (should I mention how akward naming queries is:)?)

it would be a lot nicer if the ECS class could keep track of existing queries and just return one of those when attempting to create a query with the same parameters as a previously created one

**Comment by EnderShadow8** [comment]
Good idea. You could of course implement this yourself, but I think this is a very common use case so I'll add it to the library.

**Comment by EnderShadow8** [comment]
I've thought about this for a bit, and doing a deep equality check against every query created seems a bit excessive for the problem at hand, especially since extra queries don't impact runtime performance besides taking up a small amount of extra memory. To be honest, the memory overhead of having a few duplicate queries doesn't really matter in the big picture for most use cases since speed is not affected at all.

If you find naming queries cumbersome, this might help:

```js
function System(query, sys) {
  return () => sys(query)
}

const system = System(ecs.createQuery(...), q => {
  // system code goes here
}
```

If this solves your problem then feel free to close the issue.
